dist: bionic
jobs:
  include:
  - name: Enterprise 1.5.0.x
    env: KONG_VERSION=1.5.0.x
  - name: Kong CE 1.5.x
    env: KONG_VERSION=1.5.x
  - name: Kong CE 2.0.x
    env: KONG_VERSION=2.0.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee
  #- name: Nightly CE-master
  #  env: KONG_VERSION=nightly
env:
  global:
  # for Enterprise images
  - PULP_USERNAME=admin
  - secure: I3Vy9C1z5bgO7OfyI6rkt9dvpOEaaR6hc8i/mlTYQcE+hgAq+D1HhplHhgwPh9MsImOxqeCRU4VaOk+4ZWYZsZdqUzcGFnww+Jh4rzJl207ZBeXnd05qsa4l3L5N7CNo6YGGYVrF2ZHu4BzVodFV0CEP5lZu6dJ9vIl6NoeXGDktN23mDb0bcHp4bC4CwHodWBzJp7+vc5zHsofQ5DsjQtlmGXoADCeEKfLHlZ2ZoBQTlpvkutUvMqzU3deqNw1Be9cx/i7/AXXFmODyFE82WSaVhFXNjijuHVz90SCyCxT1Jym3xS21FHwJw2skazJBouSyEYy8K996bmLZM21c3mFVfQt7YXeW5Qkh82/pLRL0eRqHnrQ08viomo4UJX94m99BifJOHD65RNv4tVlmcZLvQT/Vnwmf3n/C8FfsqbIx5G7krOzb/rY77qZX0fF2ZOg+/x5mhUk7z6wCIfQlJcaNzz1mC4qh0ysANvTdLHueSz9kk0aOykazpIm59JjTaqV2CM6TjRZRP36xdNjUw34uktbfkvSYloKOeu+flb9A/i0u8MfbhMwJUK1+76Ovr4Wrtj4TASbFXK5v+TWTHoOLYVigMDB2FPynEP723fT4x2SPT50Uy7iA+TqbxRPI6IBHQTKLcdOChgau2Wt1zpXsGyFJ6HYIfRYX1M6PGYo=
  # for Enterprise nightly images
  - DOCKER_USERNAME=kongcloudpull
  - secure: QBesLw3uiKlrEV9vybdYLEMGwRvAwmv5wG09/jfyUssoN3dFrsD8RzaFkIFlhPAhge4+Oc2LKQFE734a4kO57q9XRqNoilsTOaK4jTH6yTPrwQMxmRZw3JHKIBxVldynHaeFClJcdhiJFMZp3jcsnFZoc61MawIifVGupFatiPqrUdNVaj1GPa0WKgVF0BC8CG0oFgKIwFGp4yxHadJyuQKHqeca6adOwDnqAW0sa0nTen4nQ/ANAZDIuJZK5r4RUjCKq16SbQsyEQdCaoBkRLE1ZPNPoDbE5+u5IS21f2uQyh2G6HE8LSi/KMN0V8aeMEbPYV/Esf6MXM+2CFsvC2T2DUL2RaniOb4R/pHpsyjn8nxX/+zCj3N25/UJfaymn2sQCfbIX6PoQtfmQNjiANEXPty89bidnR5mYMOgcEySwPAhMPCs91NUZgDXTzdZ89xCtvSQcPHqrpy3S241z1GDdFJ5zwa19FBjk7mDQCHtN5P7BwKUp1ULtQjBD7xouUy8v3xpzKS0lRkKiGRSovcm9iQ3/wWN2sMJg1Dl3ytlWD6yJyO8+xYsrHq/mSX7OGgjDUvKPX6ccQAh9bAeTLWg5W9wYdlENkGTKuTmphkCD73AHDPl5eZEHTdIwD7PXSfyJFPdqPlUe9QWDTAwdS3tKHtNtYfnFCOQ0eP3ezA=
install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"
script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"
notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: cThgMERsC4Z+YA/ttVKE+QfKYNTG4lodiJCjNkzHek91jWGLulzus60hP1mqZypFQ/oNSxHvbfEGfURCkfovjMInpUpE/X8w7J8W7Wl6+gSPl+jDYbvNVIbpA8FDXijieBERoXdFd7tQxk129lUj929jaf+AIggTn4Rrgb1KWSGX8I9aUF6HKw41FqcxP8q6mtIDpUkjLbCPRtMQI/Tnr6oGUZA9HkZ8zAfo0iCiesnRGvfiFwYxTzalwhBpEvUlBRINMp3p1f5T0sA9qwX6GRBplK3X2gL0lZ67b4aV5mdQk25ORXXplDPBfU8t+X/BIJsJx/h3yAqniXc7oq7RnG74xuLbPI3dN1BRjRz+F+4vT4CtZOyuutt6EIpFvH2LJOCeh9r0VGUWUvzq1bOUOeVVIH2ud8rcVlEHSRCZQiD/tnUz8g70Xjg1SQUYYL4TZRf3dht2Qi8hZML/1ZXmOgzxJOkR4EB3HFl4iyONJA1W9EKFu591LGOSRSQhW2vNErzV5PmGfswDJGHlk89C2H26Uy1iPWQ2nqb15hGtbQ6KuPHJwgwPIji2Du/eVPS5fhVTOapGGqTD9wpXbq6kBFngalIwBZQvW9veGhQ8GqEn6BgHtg0hCs+F4LFQaq9zUcK0jCKn/G6ibUv19LBCuiVclBzKWzDwiLsHYJpg1YM=
